<?php

namespace Database\Seeders;

use App\Models\Plan;
use Illuminate\Database\Seeder;

class PlanSeeder extends Seeder
{
    public function run(): void
    {
        Plan::updateOrCreate(['slug' => 'emprende'], [
            'name' => 'EMPRENDE',
            'monthly_fee' => 0,
            'commission_rate' => 0.1500,
            'has_membership_fee' => false,
            'is_active' => true,
            'timeline_icon' => 'star',
            'badge' => null,
            'description' => 'Perfecto para empezar a vender en LYRIUM sin costo inicial.',
            'css_color' => '#9cb04e',
            'accent_color' => '#7d9940',
            'requires_payment' => false,
            'enable_claim_lock' => false,
            'claim_months' => 12,
            'subscribe_button_text' => 'Comenzar gratis',
            'currency' => 'S/',
            'period' => '/mes',
            'price_annual' => null,
            'price_text' => 'Gratis',
            'price_subtext' => 'Siempre gratis',
            'use_price_mode' => false,
            'compact_visible_count' => 4,
            'features' => [
                ['text' => 'Exposición de productos al buscar en LYRIUM', 'active' => true],
                ['text' => 'Espacio propio para personalizar tu tienda', 'active' => true],
                ['text' => 'Gestión de pedidos y inventario básico', 'active' => true],
                ['text' => 'Soporte técnico por email', 'active' => true],
            ],
            'detailed_benefits' => [
                ['emoji' => '🔍', 'title' => 'Exposición de productos', 'description' => 'Tus productos aparecerán en los resultados de búsqueda de LYRIUM', 'color' => '#9cb04e'],
                ['emoji' => '🎨', 'title' => 'Tienda personalizada', 'description' => 'Espacio propio para configurar tu tienda virtual con tu identidad de marca', 'color' => '#9cb04e'],
                ['emoji' => '📦', 'title' => 'Gestión de pedidos', 'description' => 'Administra tus pedidos e inventario de manera eficiente', 'color' => '#9cb04e'],
                ['emoji' => '📧', 'title' => 'Soporte técnico', 'description' => 'Atención técnica por email para resolver tus dudas', 'color' => '#9cb04e'],
            ],
            'capabilities' => [
                'max_products' => 20,
                'max_services' => 5,
                'max_specialists' => 1,
                'max_branches' => 2,
                'max_social_links' => 2,
                'max_gallery_images' => 5,
                'max_ad_banners' => 4,
                'max_main_banners' => 1,
                'sticker_types' => ['descuento'],
                'layouts' => ['emprende'],
                'can_training' => false,
                'can_bioblog' => true,
                'can_export_csv' => false,
                'can_export_excel' => true,
                'can_export_pdf' => false,
                'can_finance_charts' => false,
                'can_google_calendar' => false,
                'can_coupons' => false,
                'can_api' => false,
                'can_white_label' => false,
                'can_market_analysis' => false,
                'support_hours' => 48,
                'search_priority' => 'normal',
                'forum_topics_per_week' => 1,
                'bioblog_articles_per_week' => 2,
                'bioblog_videos_per_week' => 1,
                'bioblog_podcasts_per_week' => 1,
                'bioblog_shorts_per_week' => 1,
            ],
        ]);

        Plan::updateOrCreate(['slug' => 'crece'], [
            'name' => 'CRECE',
            'monthly_fee' => 40,
            'commission_rate' => 0.1500,
            'has_membership_fee' => true,
            'is_active' => true,
            'timeline_icon' => 'trending-up',
            'badge' => 'Popular',
            'description' => 'El plan ideal para hacer crecer tu negocio con herramientas avanzadas.',
            'css_color' => '#64c695',
            'accent_color' => '#4da978',
            'requires_payment' => true,
            'enable_claim_lock' => true,
            'claim_months' => 3,
            'subscribe_button_text' => 'Suscribirse',
            'currency' => 'S/',
            'period' => '/mes',
            'price_annual' => 432.00,
            'price_text' => null,
            'price_subtext' => '/mes',
            'use_price_mode' => true,
            'compact_visible_count' => 5,
            'features' => [
                ['text' => 'Todo lo del plan EMPRENDE', 'active' => true],
                ['text' => 'Logo en banners principales de LYRIUM', 'active' => true],
                ['text' => 'Capacitaciones online en postventa', 'active' => true],
                ['text' => 'Medalla de producto recomendado por LYRIUM', 'active' => true],
                ['text' => 'Atención preferencial por LYRIUM', 'active' => true],
            ],
            'detailed_benefits' => [
                ['emoji' => '🏆', 'title' => 'Logo en banners principales', 'description' => 'Tu logotipo se exhibirá en los banners principales de LYRIUM', 'color' => '#64c695'],
                ['emoji' => '🎓', 'title' => 'Capacitaciones online', 'description' => 'Accede a sesiones de capacitación online en postventa', 'color' => '#64c695'],
                ['emoji' => '⭐', 'title' => 'Producto recomendado', 'description' => 'Recibe una insignia de producto recomendado por LYRIUM', 'color' => '#64c695'],
                ['emoji' => '💬', 'title' => 'Atención preferencial', 'description' => 'Soporte prioritario para resolver tus consultas más rápido', 'color' => '#64c695'],
            ],
            'capabilities' => [
                'max_products' => 100,
                'max_services' => 20,
                'max_specialists' => 5,
                'max_branches' => 6,
                'max_social_links' => 8,
                'max_gallery_images' => 15,
                'max_ad_banners' => 16,
                'max_main_banners' => 3,
                'sticker_types' => ['liquidacion', 'oferta', 'descuento', 'nuevo', 'bestseller', 'envio_gratis'],
                'layouts' => ['1', '2', '3', 'emprende'],
                'can_training' => true,
                'can_bioblog' => true,
                'can_export_csv' => true,
                'can_export_excel' => true,
                'can_export_pdf' => true,
                'can_finance_charts' => true,
                'can_google_calendar' => false,
                'can_coupons' => true,
                'can_api' => false,
                'can_white_label' => false,
                'can_market_analysis' => false,
                'support_hours' => 24,
                'search_priority' => 'media',
                'forum_topics_per_week' => 2,
                'bioblog_articles_per_week' => 4,
                'bioblog_videos_per_week' => 4,
                'bioblog_podcasts_per_week' => 4,
                'bioblog_shorts_per_week' => 4,
            ],
        ]);

        Plan::updateOrCreate(['slug' => 'especial'], [
            'name' => 'ESPECIAL',
            'monthly_fee' => 89.90,
            'commission_rate' => 0.1500,
            'has_membership_fee' => true,
            'is_active' => true,
            'timeline_icon' => 'crown',
            'badge' => 'Premium',
            'description' => 'Máxima visibilidad y herramientas exclusivas para los mejores vendedores.',
            'css_color' => '#499bbf',
            'accent_color' => '#357fa3',
            'requires_payment' => true,
            'enable_claim_lock' => true,
            'claim_months' => 6,
            'subscribe_button_text' => 'Suscribirse',
            'currency' => 'S/',
            'period' => '/mes',
            'price_annual' => 899.00,
            'price_text' => null,
            'price_subtext' => '/mes',
            'use_price_mode' => true,
            'compact_visible_count' => 5,
            'features' => [
                ['text' => 'Todo lo del plan CRECE', 'active' => true],
                ['text' => 'Banner personalizado en homepage de LYRIUM', 'active' => true],
                ['text' => 'Servicio de atención al cliente personalizado', 'active' => true],
                ['text' => 'Análisis de mercado y competidores', 'active' => true],
                ['text' => 'Prioridad en búsquedas y filtros', 'active' => true],
            ],
            'detailed_benefits' => [
                ['emoji' => '🖼️', 'title' => 'Banner personalizado', 'description' => 'Tu banner personalizado aparecerá en el homepage de LYRIUM', 'color' => '#499bbf'],
                ['emoji' => '👤', 'title' => 'Atención al cliente personalizada', 'description' => 'Servicio dedicado de atención al cliente para ti', 'color' => '#499bbf'],
                ['emoji' => '📊', 'title' => 'Análisis de mercado', 'description' => 'Reports y análisis de mercado y competidores', 'color' => '#499bbf'],
                ['emoji' => '🔝', 'title' => 'Prioridad en búsquedas', 'description' => 'Tus productos aparecerán primero en búsquedas y filtros', 'color' => '#499bbf'],
            ],
            'capabilities' => [
                'max_products' => -1,
                'max_services' => -1,
                'max_specialists' => -1,
                'max_branches' => 6,
                'max_social_links' => 8,
                'max_gallery_images' => -1,
                'max_ad_banners' => 16,
                'max_main_banners' => 3,
                'sticker_types' => ['liquidacion', 'oferta', 'descuento', 'nuevo', 'bestseller', 'envio_gratis'],
                'layouts' => ['1', '2', '3', 'emprende'],
                'can_training' => true,
                'can_bioblog' => true,
                'can_export_csv' => true,
                'can_export_excel' => true,
                'can_export_pdf' => true,
                'can_finance_charts' => true,
                'can_google_calendar' => true,
                'can_coupons' => true,
                'can_api' => true,
                'can_white_label' => true,
                'can_market_analysis' => true,
                'support_hours' => 4,
                'search_priority' => 'alta',
                'forum_topics_per_week' => 2,
                'bioblog_articles_per_week' => 4,
                'bioblog_videos_per_week' => 4,
                'bioblog_podcasts_per_week' => 4,
                'bioblog_shorts_per_week' => 4,
            ],
        ]);

        // Plan "Crece - Por Vida": pago único, mismas capacidades que Crece.
        // is_active=true para que /admin/plans y /plans lo devuelvan (así el frontend
        // puede resolver su numericId al comprarlo), pero el frontend lo excluye
        // deliberadamente de la grilla de tarjetas (no es un plan más, es una duración
        // especial dentro de la tarjeta de Crece).
        $crece = Plan::where('slug', 'crece')->first();
        Plan::updateOrCreate(['slug' => 'crece-lifetime'], [
            'name' => 'Crece - Por Vida',
            'monthly_fee' => 0,
            'is_lifetime' => true,
            'lifetime_price' => 1500.00,
            'commission_rate' => 0.1500,
            'has_membership_fee' => true,
            'is_active' => true,
            'timeline_icon' => 'trending-up',
            'badge' => 'Por Vida',
            'description' => 'Todo lo del plan Crece, con un único pago y sin renovaciones.',
            'css_color' => '#64c695',
            'accent_color' => '#4da978',
            'requires_payment' => true,
            'enable_claim_lock' => false,
            'claim_months' => 1,
            'subscribe_button_text' => 'Suscribirse de por vida',
            'currency' => 'S/',
            'period' => '/vida',
            'price_annual' => null,
            'price_text' => 'S/ 1500',
            'price_subtext' => 'pago único',
            'use_price_mode' => true,
            'compact_visible_count' => 5,
            'features' => $crece?->features ?? [],
            'detailed_benefits' => $crece?->detailed_benefits ?? [],
            'capabilities' => $crece?->capabilities ?? [],
        ]);
    }
}
