<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\Store;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        config(['scout.driver' => null]);

        $store = Store::where('slug', 'biotienda-demo')->first();

        if (! $store) {
            $this->command->warn('Store biotienda-demo not found. Skipping ProductSeeder.');

            return;
        }

        $products = [
            [
                'name' => 'Semillas de Chía Orgánicas',
                'slug' => 'semillas-chia-organicas',
                'description' => 'Semillas de chía certificadas orgánicas, ricas en omega-3 y antioxidantes. Ideales para smoothies, bowls y recetas saludables.',
                'short_description' => 'Semillas orgánicas ricas en omega-3',
                'price' => 24.90,
                'regular_price' => 29.90,
                'stock' => 150,
                'weight' => 0.5,
                'sticker' => 'organic',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-SEM-001',
                'rating_promedio' => 4.8,
                'rating_count' => 124,
                'categories' => ['semillas', 'alimentos-organicos'],
            ],
            [
                'name' => 'Aceite de Coco Virgen Extra',
                'slug' => 'aceite-coco-virgen-extra',
                'description' => 'Aceite de coco prensado en frío, 100% puro y orgánico. Perfecto para cocinar, cosmética natural y cuidado del cabello.',
                'short_description' => 'Aceite de coco prensado en frío, 100% orgánico',
                'price' => 32.00,
                'regular_price' => 38.00,
                'stock' => 80,
                'weight' => 1.0,
                'sticker' => 'natural',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-ACE-001',
                'rating_promedio' => 4.9,
                'rating_count' => 89,
                'categories' => ['aceites-esenciales', 'alimentos-organicos'],
            ],
            [
                'name' => 'Fertilizante Orgánico Líquido',
                'slug' => 'fertilizante-organico-liquido',
                'description' => 'Fertilizante líquido 100% orgánico para plantas domésticas y huertos. A base de extracto de algas marinas y compost.',
                'short_description' => 'Fertilizante líquido orgánico para plantas',
                'price' => 18.50,
                'regular_price' => 22.00,
                'stock' => 200,
                'weight' => 1.2,
                'sticker' => 'eco',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-FER-001',
                'rating_promedio' => 4.5,
                'rating_count' => 67,
                'categories' => ['fertilizantes'],
            ],
            [
                'name' => 'Té Verde Matcha Ceremonial Premium',
                'slug' => 'te-verde-matcha-ceremonial',
                'description' => 'Matcha ceremonial de primera calidad, cultivado en sombra para máxima concentración de clorofila y antioxidantes.',
                'short_description' => 'Matcha ceremonial premium de Japón',
                'price' => 45.00,
                'regular_price' => 55.00,
                'stock' => 60,
                'weight' => 0.1,
                'sticker' => 'premium',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-ALI-001',
                'rating_promedio' => 4.7,
                'rating_count' => 203,
                'categories' => ['alimentos-organicos', 'productos-naturales'],
            ],
            [
                'name' => 'Jabón de Castilla Natural',
                'slug' => 'jabon-castilla-natural',
                'description' => 'Jabón artesanal de aceite de oliva, hipoalergénico y sin fragancias. Apto para pieles sensibles y uso diario.',
                'short_description' => 'Jabón artesanal hipoalergénico',
                'price' => 12.00,
                'regular_price' => 14.00,
                'stock' => 300,
                'weight' => 0.15,
                'sticker' => 'natural',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-CUI-001',
                'rating_promedio' => 4.6,
                'rating_count' => 156,
                'categories' => ['cuidado-personal', 'productos-naturales'],
            ],
            [
                'name' => 'Kit de Semillas para Huerto Urbano',
                'slug' => 'kit-semillas-huerto-urbano',
                'description' => 'Kit con 10 variedades de semillas orgánicas para cultivar tu propio huerto en casa. Incluye tomate, lechuga, albahaca, pimiento y más.',
                'short_description' => '10 variedades de semillas para huerto urbano',
                'price' => 35.00,
                'regular_price' => 35.00,
                'stock' => 45,
                'weight' => 0.3,
                'sticker' => 'eco',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-HER-001',
                'rating_promedio' => 4.4,
                'rating_count' => 38,
                'categories' => ['semillas', 'herramientas'],
            ],
            [
                'name' => 'Probióticos Flora Intestinal',
                'slug' => 'probióticos-flora-intestinal',
                'description' => 'Suplemento de probióticos con 50 mil millones de UFC. 10 cepas diferentes para здоровый кишечник y sistema inmunológico.',
                'short_description' => 'Probióticos 50B UFC, 10 cepas',
                'price' => 58.00,
                'regular_price' => 68.00,
                'stock' => 120,
                'weight' => 0.08,
                'sticker' => 'organic',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-SUP-001',
                'rating_promedio' => 4.3,
                'rating_count' => 91,
                'categories' => ['suplementos', 'productos-naturales'],
            ],
            [
                'name' => 'Aceite Esencial de Lavanda',
                'slug' => 'aceite-esencial-lavanda',
                'description' => 'Aceite esencial de lavanda 100% puro, destilado al vapor. Ideal para aromaterapia, relajación y cuidado de la piel.',
                'short_description' => 'Aceite esencial 100% puro de lavanda',
                'price' => 22.00,
                'regular_price' => 26.00,
                'stock' => 95,
                'weight' => 0.05,
                'sticker' => 'natural',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-ACE-002',
                'rating_promedio' => 4.8,
                'rating_count' => 178,
                'categories' => ['aceites-esenciales', 'cuidado-personal'],
            ],
            [
                'name' => 'Miel de Abeja Silvestre',
                'slug' => 'miel-abeja-silvestre',
                'description' => 'Miel pura de abeja silvestre, cosechada en zonas libres de pesticides. Sabor intenso y propiedades antibacterianas naturales.',
                'short_description' => 'Miel pura de abeja silvestre, libre de pesticides',
                'price' => 38.00,
                'regular_price' => 45.00,
                'stock' => 70,
                'weight' => 0.5,
                'sticker' => 'organic',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-ALI-002',
                'rating_promedio' => 4.9,
                'rating_count' => 245,
                'categories' => ['alimentos-organicos', 'productos-naturales'],
            ],
            [
                'name' => 'Tijeras de Poda de Acero Inoxidable',
                'slug' => 'tijeras-poda-acero-inoxidable',
                'description' => 'Tijeras de poda profesionales de acero inoxidable, ergonómicas yafiladas. Ideales para Bonsái y plantas de interior.',
                'short_description' => 'Tijeras de poda profesionales de acero',
                'price' => 28.00,
                'regular_price' => 28.00,
                'stock' => 55,
                'weight' => 0.2,
                'sticker' => null,
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-HER-002',
                'rating_promedio' => 4.2,
                'rating_count' => 44,
                'categories' => ['herramientas'],
            ],
            [
                'name' => 'Crema Hidratante de Aloe Vera',
                'slug' => 'crema-hidratante-aloe-vera',
                'description' => 'Crema facial hidratante con aloe vera orgánico y aceite de jojoba. Sin parabenos, Cruelty-free y vegana.',
                'short_description' => 'Crema hidratante orgánica con aloe vera',
                'price' => 42.00,
                'regular_price' => 48.00,
                'stock' => 88,
                'weight' => 0.1,
                'sticker' => 'vegan',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-CUI-002',
                'rating_promedio' => 4.5,
                'rating_count' => 132,
                'categories' => ['cuidado-personal', 'productos-naturales'],
            ],
            [
                'name' => 'Abono de Lombriz 5kg',
                'slug' => 'abono-lombriz-5kg',
                'description' => 'Abono orgánico de lombriz, mejorado con microorganismos эффективных. Ideal para huerto y jardín.',
                'short_description' => 'Abono orgánico de lombriz EM',
                'price' => 25.00,
                'regular_price' => 30.00,
                'stock' => 110,
                'weight' => 5.0,
                'sticker' => 'eco',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-FER-002',
                'rating_promedio' => 4.6,
                'rating_count' => 77,
                'categories' => ['fertilizantes'],
            ],
            [
                'name' => 'Cacao Puro en Polvo',
                'slug' => 'cacao-puro-polvo',
                'description' => 'Cacao en polvo 100% puro, sin azúcar añadida. Rico en antioxidantes y magnesio. Procedente de comercio justo.',
                'short_description' => 'Cacao puro 100%, comercio justo',
                'price' => 19.00,
                'regular_price' => 24.00,
                'stock' => 140,
                'weight' => 0.25,
                'sticker' => 'organic',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-ALI-003',
                'rating_promedio' => 4.7,
                'rating_count' => 198,
                'categories' => ['alimentos-organicos'],
            ],
            [
                'name' => 'Kit de Cosmética Natural DIY',
                'slug' => 'kit-cosmetica-natural-diy',
                'description' => 'Kit completo para elaborar tus propios productos de cosmética natural en casa. Incluye arcilla, aceites y recetas.',
                'short_description' => 'Kit DIY de cosmética natural con 5 recetas',
                'price' => 65.00,
                'regular_price' => 75.00,
                'stock' => 30,
                'weight' => 1.5,
                'sticker' => 'natural',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-CUI-003',
                'rating_promedio' => 4.4,
                'rating_count' => 25,
                'categories' => ['cuidado-personal', 'productos-naturales'],
            ],
            [
                'name' => 'Guano de Murciélago 1kg',
                'slug' => 'guano-murcielago-1kg',
                'description' => 'Fertilizante natural de guano de murciélago, alto en fósforo y potasio. Ideal para floración y fructificación.',
                'short_description' => 'Guano de murciélago rico en P y K',
                'price' => 15.00,
                'regular_price' => 18.00,
                'stock' => 180,
                'weight' => 1.0,
                'sticker' => 'organic',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-FER-003',
                'rating_promedio' => 4.3,
                'rating_count' => 56,
                'categories' => ['fertilizantes'],
            ],
            [
                'name' => 'Aspersor de Jardín Giratorio',
                'slug' => 'aspersor-jardin-giratorio',
                'description' => 'Aspersor oscilante de jardín con 18 boquillas, cobertura uniforme. Resistente a UV y duradero.',
                'short_description' => 'Aspersor oscilante 18 boquillas',
                'price' => 35.00,
                'regular_price' => 40.00,
                'stock' => 65,
                'weight' => 0.8,
                'sticker' => null,
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-HER-003',
                'rating_promedio' => 4.1,
                'rating_count' => 33,
                'categories' => ['herramientas'],
            ],
            [
                'name' => 'Vitamina C Liposomal 1000mg',
                'slug' => 'vitamina-c-liposomal-1000mg',
                'description' => 'Suplemento de vitamina C en presentación liposomal para mejor absorción. Con escaramujo y bioflavonoides.',
                'short_description' => 'Vitamina C liposomial de alta absorción',
                'price' => 48.00,
                'regular_price' => 55.00,
                'stock' => 100,
                'weight' => 0.15,
                'sticker' => 'organic',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-SUP-002',
                'rating_promedio' => 4.6,
                'rating_count' => 142,
                'categories' => ['suplementos'],
            ],
            [
                'name' => 'Hidrolato de Rosa Mosqueta',
                'slug' => 'hidrolato-rosa-mosqueta',
                'description' => 'Hidrolato puro de rosa mosqueta,lenador y nutritivo. Excelente tónico facial y fijador de maquillaje natural.',
                'short_description' => 'Hidrolato puro de rosa mosqueta',
                'price' => 28.00,
                'regular_price' => 33.00,
                'stock' => 75,
                'weight' => 0.2,
                'sticker' => 'natural',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-ACE-003',
                'rating_promedio' => 4.7,
                'rating_count' => 88,
                'categories' => ['aceites-esenciales', 'cuidado-personal'],
            ],
            [
                'name' => 'Grindelia Segura para Resfriados',
                'slug' => 'grindelia-segura-resfriados',
                'description' => 'Tintura madre de grindelia, planta expectorante y antiespasmódica. Para toss y congestión respiratoria.',
                'short_description' => 'Tintura de grindelia para vias respiratorias',
                'price' => 19.00,
                'regular_price' => 22.00,
                'stock' => 90,
                'weight' => 0.05,
                'sticker' => 'natural',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-SUP-003',
                'rating_promedio' => 4.2,
                'rating_count' => 41,
                'categories' => ['suplementos', 'productos-naturales'],
            ],
            [
                'name' => 'Polen de Abeja Granulado',
                'slug' => 'polen-abeja-granulado',
                'description' => 'Polen de abeja fresco y congelado, seco. Rico en proteínas, vitaminas del grupo B y aminoácidos esenciales.',
                'short_description' => 'Polen de abeja fresco, rico en proteínas',
                'price' => 29.00,
                'regular_price' => 34.00,
                'stock' => 50,
                'weight' => 0.25,
                'sticker' => 'organic',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-ALI-004',
                'rating_promedio' => 4.5,
                'rating_count' => 67,
                'categories' => ['alimentos-organicos', 'suplementos'],
            ],
            // SERVICIOS - Las mejores ofertas de Servicios
            [
                'name' => 'Ecografía Obstétrica',
                'slug' => 'ecografia-obstetrica',
                'description' => 'Ecografía obstétrica de alta resolución para seguimiento del embarazo. Imágenes 4D del bebé.',
                'short_description' => 'Ecografía obstétrica 4D',
                'price' => 120.00,
                'regular_price' => 150.00,
                'stock' => 10,
                'sticker' => 'oferta',
                'status' => 'approved',
                'type' => 'service',
                'sku' => 'SER-ECO-001',
                'rating_promedio' => 4.9,
                'rating_count' => 45,
                'categories' => ['servicios-medicos'],
                'image' => '/storage/img/productos/Ecografía obstetrica.png',
                'service_duration' => 30,
                'service_modality' => 'presencial',
                'service_location' => 'Consultorio médico',
            ],
            [
                'name' => 'Profilaxis y Destartraje con Fluor',
                'slug' => 'profilaxis-destartraje-fluor',
                'description' => 'Limpieza dental profesional con ultrasonido, pulido y aplicación de fluoruro. Previene caries y enfermedades periodontales.',
                'short_description' => 'Limpieza dental con fluor',
                'price' => 80.00,
                'regular_price' => 100.00,
                'stock' => 20,
                'sticker' => 'oferta',
                'status' => 'approved',
                'type' => 'service',
                'sku' => 'SER-DEN-001',
                'rating_promedio' => 4.8,
                'rating_count' => 89,
                'categories' => ['servicios-medicos'],
                'image' => '/storage/img/productos/Profilaxis DestartajeFluor.png',
                'service_duration' => 45,
                'service_modality' => 'presencial',
                'service_location' => 'Clínica dental',
            ],
            [
                'name' => 'Riquezas Campesinas - Pack Saludable',
                'slug' => 'riquezas-campesinas-pack',
                'description' => 'Servicio de asesoría nutricional personalizada con productos orgánicos de productores locales.',
                'short_description' => 'Asesoría nutricional con productos orgánicos',
                'price' => 95.00,
                'regular_price' => 120.00,
                'stock' => 15,
                'sticker' => 'oferta',
                'status' => 'approved',
                'type' => 'service',
                'sku' => 'SER-NUT-001',
                'rating_promedio' => 4.7,
                'rating_count' => 32,
                'categories' => ['servicios-medicos'],
                'image' => '/storage/img/productos/riquezas-campesinas.png',
                'service_duration' => 60,
                'service_modality' => 'presencial',
                'service_location' => 'Domicilio del cliente',
            ],

            // PRODUCTOS FÍSICOS - Las mejores ofertas de Productos
            [
                'name' => 'Blanqueamiento Dental Profesional',
                'slug' => 'blanqueamiento-dental-profesional',
                'description' => 'Kit de blanqueamiento dental profesional con gel de peróxido de hidrógeno. Resultados visibles en 7 días.',
                'short_description' => 'Kit blanqueamiento dental profesional',
                'price' => 89.00,
                'regular_price' => 149.00,
                'stock' => 50,
                'sticker' => 'oferta',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-BLAN-001',
                'rating_promedio' => 4.6,
                'rating_count' => 78,
                'categories' => ['productos-belleza'],
                'image' => '/storage/img/productos/servicios-medicos/blanqueamiento-dental.png',
            ],
            [
                'name' => 'Diagnóstico Unipolar de Salud',
                'slug' => 'diagnostico-unipolar-salud',
                'description' => 'Servicio de diagnóstico de salud integral con análisis de laboratorio completo y consulta médica especializada.',
                'short_description' => 'Diagnóstico integral de salud',
                'price' => 199.00,
                'regular_price' => 350.00,
                'stock' => 20,
                'sticker' => 'oferta',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-DIAG-001',
                'rating_promedio' => 4.8,
                'rating_count' => 45,
                'categories' => ['productos-suplementos'],
                'image' => '/storage/img/productos/servicios-medicos/Diagnostico unipolar.png',
            ],
            [
                'name' => 'Masajes Corporales Relajantes',
                'slug' => 'masajes-corporales-relajantes',
                'description' => 'Pack de 5 sesiones de masaje corporal relajante con aceites esenciales naturales. Incluye consulta previa.',
                'short_description' => 'Pack 5 sesiones masaje corporal',
                'price' => 250.00,
                'regular_price' => 400.00,
                'stock' => 30,
                'sticker' => 'oferta',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-MASA-001',
                'rating_promedio' => 4.9,
                'rating_count' => 112,
                'categories' => ['productos-belleza'],
                'image' => '/storage/img/productos/servicios-medicos/masajes-corporales.png',
            ],
            [
                'name' => 'Programas de Rehabilitación Integral',
                'slug' => 'programas-rehabilitacion-integral',
                'description' => 'Programa completo de rehabilitación física de 12 semanas con seguimiento personalizado y ejercicios adaptados.',
                'short_description' => 'Programa rehabilitación 12 semanas',
                'price' => 599.00,
                'regular_price' => 899.00,
                'stock' => 15,
                'sticker' => 'oferta',
                'status' => 'approved',
                'type' => 'physical',
                'sku' => 'BIO-REHA-001',
                'rating_promedio' => 4.7,
                'rating_count' => 34,
                'categories' => ['productos-bienestar-fisico'],
                'image' => '/storage/img/productos/belleza/banner-principal-cremas.png',
            ],
        ];

        foreach ($products as $data) {
            $categories = $data['categories'] ?? [];
            $image = $data['image'] ?? null;
            unset($data['categories']);
            unset($data['sticker']);
            unset($data['image']);

            if (Product::where('slug', $data['slug'])->exists()) {
                continue;
            }

            $productData = array_merge($data, [
                'store_id' => $store->id,
                'discount_percentage' => $data['regular_price'] > $data['price']
                    ? round((($data['regular_price'] - $data['price']) / $data['regular_price']) * 100, 2)
                    : 0,
            ]);

            if ($image) {
                $productData['image'] = $image;
            }

            $product = Product::create($productData);

            foreach ($categories as $catSlug) {
                $category = Category::where('slug', $catSlug)->first();
                if ($category) {
                    $product->categories()->attach($category->id);
                }
            }

            $product->save();
        }

        $this->command->info('ProductSeeder: '.Product::count().' products seeded.');
    }
}
