# must be unique in a given SonarQube Server instance
sonar.projectKey=lyrium-backend

sonar.host.url=http://localhost:9000
sonar.token=sqp_a29d3beb7ffded964f3750cb168ab59ca0e19139

sonar.sources=app,database,routes,resources/views,config
sonar.exclusions=**/node_modules/**,**/.next/**,**/vendor/**
sonar.sourceEncoding=UTF-8
sonar.php.version=8.2