<?php

declare(strict_types=1);

return [

    'blocked_words' => [

        'profanity' => [
            'cojones',
            'coño',
            'carajo',
            'mierda',
            'puta',
            'puto',
            'putas',
            'putos',
            'pendejo',
            'pendeja',
            'weon',
            'weona',
            'wn',
            'aweonao',
            'aweonado',
            'conchetumare',
            'conchetumadre',
            'conchatumare',
            'conchatumadre',
            'conchesumare',
            'hijueputa',
            'hijueputa',
            'hp',
            'ctm',
            'mrd',
            'culeado',
            'culiao',
            'culera',
            'culero',
            'marica',
            'maricon',
            'maricón',
            'cagado',
            'cagar',
            'chucha',
            'sorete',
            'chupamela',
            'tarado',
            'tarada',
            'imbecil',
            'imbécil',
            'estupido',
            'estúpido',
            'pendejada',
            'pendejadas',
            'huevada',
            'huevadas',
            'huevon',
            'huevón',
            'huevona',
            'baboso',
            'babosa',
            'pajero',
            'pajera',
            'puta madre',
            'la concha',
            'tu madre',
        ],

        'terrorism' => [
            'terrorismo',
            'terrorista',
            'atentado',
            'bomba',
            'explosivo',
            'matar',
            'asesinar',
            'secuestrar',
            'extorsionar',
            'sabotaje',
            'insurgente',
            'guerrilla',
            'narcoterrorismo',
            'sendero luminoso',
            'mrta',
            'al qaeda',
            'estado islámico',
            'estado islamico',
            'talibán',
            'taliban',
            'yihad',
            'jihad',
            'célula terrorista',
            'ataque suicida',
        ],

        'politics' => [
            'politico corrupto',
            'política corrupta',
            'partido politico',
            'gobierno corrupto',
            'dictadura',
            'comunismo',
            'socialismo',
            'fascismo',
            'nazi',
            'extremista',
            'radical',
            'perú libre',
            'fujimori',
            'pedro castillo',
            'dina boluarte',
            'keiko',
            'alan garcía',
            'alan garcia',
            'ppk',
            'vizcarra',
            'toledo',
            'humala',
            'vladimir cerron',
            'antauro',
            'golpe de estado',
            'revolución',
            'revolucion',
        ],

        'spam' => [
            'click aqui',
            'clic aquí',
            'gana dinero',
            'compra ahora',
            'oferta limitada',
            'www.',
            'http://',
            'https://',
            'sigueme',
            'suscribete',
            'suscríbete',
        ],

    ],

    'messages' => [
        'profanity' => 'Tu mensaje contiene lenguaje inapropiado. Por favor, edita tu comentario.',
        'terrorism' => 'Tu mensaje contiene referencias a terrorismo, lo cual no está permitido en esta plataforma.',
        'politics' => 'Tu mensaje contiene referencias políticas. Por favor, mantén un tono neutral y respetuoso.',
        'spam' => 'Tu mensaje ha sido detectado como posible spam. Por favor, elimina los enlaces o contenido promocional.',
    ],

];
